MODIFT : SocialLogin
wecode-bootcamp-korea/16-2nd-starbugs-backend pull request #13
Opened 2021-02-01 12:51 UTC by jinukix

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-02-02 06:27 UTC, lordmyshepherd requested changes

2021-02-02 06:27 UTC, lordmyshepherd commented on user/views.py
> +                age    = kakao_data['kakao_account']['age_range'],
나중에 카카오유저의 나이가 업데이트된다면, user를 제대로 찾을 수 있을까요?

2021-02-02 07:00 UTC, jinukix commented on user/views.py
> +                age    = kakao_data['kakao_account']['age_range'],
Authentication 을 카카오 로그인으로만 할 예정인데, 카카오에서 정확한 연령정보는 가져올 수 없게 설정 되어 있습니다.
user 의 나이를 추적하려면 저희가 따로 유저의 나이를 입력하도록 해야 하는데, 그러려면 자체적인 회원가입 뷰를 만들어야 할 것 같은데, 어떻게 할까요?

2021-02-02 08:02 UTC, lordmyshepherd commented on user/views.py
> +                age    = kakao_data['kakao_account']['age_range'],
처음에 `{ 'email' : 'test@naver.com', 'gender' : 'a', 'age_range' : '10~20'}` 데이터가 들어오면 해당 유저를 생성하고, 다음에 동일한 요청에도 같은 유저가 조회됩니다.
이후에 age_range가 업데이트된다면, `{ 'email' : 'test@naver.com', 'gender' : 'a', 'age_range' : '20~30'}` 값으로 들어오게 됩니다.
이경우, 'email' : 'test@naver.com', 'gender' : 'a', 'age_range' : '20~30' 세가지 값을 기준으로 get()이 실행되기 때문에, 새로운 유저가 생성됩니다.

`get_or_create()`를 사용하시면,  email 또는 kakao user의 고유 id를 기준으로만 판단하는 것이 좋습니다.

2021-02-02 10:23 UTC, jinukix commented on user/views.py
> +                age    = kakao_data['kakao_account']['age_range'],
이해했습니다! 자세한 설명감사합니다!!

2021-02-03 01:21 UTC, soheon-lee commented on product/views.py
> +                } for nutrition in drink.nutritions.select_related("size")],
34번 줄에서 select_related 지정하신 size 속성도 9번줄에서 allergies와 함께 미리 캐싱해두시는 것이 좋을 것 같습니다

2021-02-03 01:21 UTC, soheon-lee commented on product/views.py
> +            return JsonResponse({'error' : "Drink does not exist"}, status=400)
```suggestion

        except Drink.DoesNotExist:
            return JsonResponse({'error' : "Drink does not exist"}, status=400)
```
에러메세지는 보통 대문자+언더바 조합으로 많이 지정합니다 :)

2021-02-03 01:21 UTC, soheon-lee commented on user/utils.py
> +
여기도 에러메세지 형식 수정해서 통일해주세요 :)

2021-02-03 01:36 UTC, jinukix commented on product/views.py
> +                } for nutrition in drink.nutritions.select_related("size")],
소헌님 이부분은 productdetailview에서 수정해서 올리도록 하겠습니다!

2021-02-03 02:36 UTC, soheon-lee commented
@jinukix 진욱님 커밋 메세지에는 이 코드들이 어떤 역할을 하는지에 대한 정보가 꼭 포함되어 있어야 합니다
`complete clear`라는 커밋 메세지는 그 어떤 정보도 주지 못하고 있어요.
어떤 작업을 하셨는지 구체적으로 적어서 커밋 메세지 수정해주세요~

2021-02-03 05:05 UTC, soheon-lee commented
LGTM

2021-02-03 05:05 UTC, merged