Product list 부분 완료
wecode-bootcamp-korea/16-2nd-starbugs-backend pull request #7
Opened 2021-01-29 07:12 UTC by xchdtk

product list 부분 완료

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-30 13:06 UTC, ulfrid requested changes
확인 바랍니다.

2021-01-30 13:06 UTC, devops-andrew commented on product/models.py
> +
필요없는 빈칸은 제거해주세요.

2021-01-30 13:06 UTC, devops-andrew commented on product/models.py
> +
마찬가지

2021-01-30 13:06 UTC, ulfrid commented on product/tests.py
> +        Nutrition.objects.all().delete()
아래 클래스 setUp 아래로 옮겨주세요.

2021-01-30 13:06 UTC, ulfrid commented on product/views.py
> +            drink_list = []
서브카테고리 기준으로 서브카테고리 정보 및 그에 따른 음료 제품 리스트를 뿌리는 거라면,
리스트 컴프리헨션 사용을 해주세요. 지금 코드는 비효율 적이네요.

2021-02-02 02:47 UTC, jamessoun93 requested changes

2021-02-02 02:47 UTC, jamessoun93 commented on order/migrations/0001_initial.py
> +>>>>>>> f48d832 (product 부분 수정)
?!?!?!?!?!

2021-02-02 02:47 UTC, jamessoun93 commented on product/migrations/0001_initial.py
> +>>>>>>> f48d832 (product 부분 수정)
?!?!!??!!?

2021-02-02 02:47 UTC, jamessoun93 commented on product/tests.py
> +from django.test    import Client, TestCase
conflict 해결 제대로 안된채 올라온 파일이 많네요. 전부 확인해서 수정해주세요.

2021-02-02 08:07 UTC, lordmyshepherd requested changes

2021-02-02 08:07 UTC, lordmyshepherd commented on product/tests.py
> +    def setUp(self):
**setUp()**
`TestCase`를 상속받은 경우, `setUp()`은 각각의 `test_method`가 실행될 때마다 실행됩니다. 
그렇기 때문에 테스트 중에 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
ex)
```python
    def setUp(self):
        user = User.objects.create(name="a")

    def test_xxxx(self):
        user.name = "b"
        user.save()
        ....
```
이런 경우가 아니라면, 즉 test 전체에서 사용되는 수정되거나 변경되지 않을 객체들을 생성하는 경우에 `setUp`에서 객체를 생성하게 되면 매번 객체를 생성하게 되므로 느려집니다.

**setUpTestData()**
테스트에서 읽기 전용 데이터로만 사용하는 객체의 경우 class method인 `setUpTestData`를 사용하면 한번만 생성할 수 있게 되므로 테스트 처리 속도가 빨라집니다.
가급적이면 `setUp`에서 매번 객체를 생성하는 것을 지양하는 것이 좋습니다.

2021-02-02 10:08 UTC, soheon-lee commented on product/tests.py
> +
깔끔한 코드를 위해 불필요한 공백은 제거해주세요

2021-02-02 10:08 UTC, soheon-lee commented on product/tests.py
> +
깔끔한 코드를 위해 불필요한 공백과 테스트를 위한 print문은 제거해주세요

2021-02-02 10:08 UTC, soheon-lee commented on product/tests.py
> +        print(response.json())
파일 곳곳에 있는 print문 모두 삭제해주세요

2021-02-02 10:08 UTC, soheon-lee commented on product/tests.py
> +                                                                )
일렬로 모두 맞추는 것은 데이터 포함 구조를 시각적으로 표현할 수가 없습니다 진수님 :)
indentation 구조에 맞게 계층 나눠주세요

2021-02-02 10:08 UTC, soheon-lee commented on product/views.py
> +                'caffeine'   : drink.nutritions.all()[0].caffeine
```suggestion
                'size'       : drink.nutritions.first().size.name,
                'kcal'       : drink.nutritions.first().kcal,
                'sodium'     : drink.nutritions.first().sodium,
                'saturation' : drink.nutritions.all()[0].saturation,
                'sugar'      : drink.nutritions.all()[0].sugar,
                'protein'    : drink.nutritions.all()[0].protein,
                'caffeine'   : drink.nutritions.all()[0].caffeine
```
drink의 nutrition 속성이 한세트인 걸로 이해했는데 맞나요?
어차피 하나 밖에 없는 속성이라면 `first()` 메소드를 한 번 활용해보시죠! :)

2021-02-02 10:08 UTC, soheon-lee commented on product/views.py
> +            } for drink in Drink.objects.filter(sub_category=subcategory)]
Drink 클래스에 다시 접근하시기 보다는 subcategory속성에 역참조로 연결되어 있는 속성을 활용해서 해당 subcategory를 참조하고 있는 drink 객체들에 접근 해보세요 :)

2021-02-02 10:08 UTC, soheon-lee commented on product/views.py
> +        }for subcategory in SubCategory.objects.prefetch_related('drinks__nutritions').filter(**filter_set)]
`filter dictionary unpacking` good good ! v

2021-02-02 10:08 UTC, soheon-lee commented on product/views.py
> +
깔끔한 코드를 위해 불필요한 공백을 없애는 훈련을 많이 하셔야할 것 같습니다 진수님
반복적으로 이렇게 많은 공백을 넣으시다는 건 진수님 습관의 문제인 것 같아서 고치시는 게 좋겠어요

2021-02-02 11:33 UTC, soheon-lee commented on product/views.py
> +        }for subcategory in SubCategory.objects.prefetch_related('drinks__nutritions').filter(**filter_set)]
진수님 이렇게 코드 작성하시면 한 카테고리 내부에서 계속 똑같은 drink만 표출되지 않나요?

2021-02-02 11:43 UTC, soheon-lee commented on product/views.py
> +        subcategory      = SubCategory.objects.prefetch_related('drinks__nutritions')[0]
늘 모든 경우에 subcategory를 특정한 한 개의 데이터만 가져오시는건가요?

2021-02-02 11:43 UTC, soheon-lee commented on product/views.py
> +        subcategory      = SubCategory.objects.prefetch_related('drinks__nutritions')[0]
사용되는 변수인가요?

2021-02-03 01:15 UTC, soheon-lee commented
LGTM!

2021-02-03 01:15 UTC, merged